name: location_tracker_exam
description: A Flutter technical assessment demonstrating Clean Architecture, BLoC, location tracking, and Hive local storage.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.2.0

  # Location
  geolocator: ^14.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Hive Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/mock/
